default-hostname
*** Reading remote logs from Cloud Logging.
[2025-09-20 15:20:17.690649+00:00] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20 15:20:17.753233+00:00] {taskinstance.py:2616} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_backfilling_dag.delete_dataproc_cluster manual__2025-09-20T15:13:26+00:00 [queued]>
[2025-09-20 15:20:17.774167+00:00] {taskinstance.py:2616} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_backfilling_dag.delete_dataproc_cluster manual__2025-09-20T15:13:26+00:00 [queued]>
[2025-09-20 15:20:17.774892+00:00] {taskinstance.py:2869} INFO - Starting attempt 1 of 2
[2025-09-20 15:20:17.803479+00:00] {taskinstance.py:2892} INFO - Executing <Task(DataprocDeleteClusterOperator): delete_dataproc_cluster> on 2025-09-20 15:13:26+00:00
[2025-09-20 15:20:17.821034+00:00] {standard_task_runner.py:72} INFO - Started process 4738 to run task
[2025-09-20 15:20:17.833624+00:00] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'orders_backfilling_dag', 'delete_dataproc_cluster', 'manual__2025-09-20T15:13:26+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/airflow_orders_job.py', '--cfg-path', '/tmp/tmpjkuqik5a']
[2025-09-20 15:20:17.834240+00:00] {standard_task_runner.py:105} INFO - Job 18: Subtask delete_dataproc_cluster
[2025-09-20 15:20:17.933907+00:00] {task_command.py:473} INFO - Running <TaskInstance: orders_backfilling_dag.delete_dataproc_cluster manual__2025-09-20T15:13:26+00:00 [running]> on host airflow-worker-4s49s
[2025-09-20 15:20:18.149126+00:00] {taskinstance.py:3136} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='orders_backfilling_dag' AIRFLOW_CTX_TASK_ID='delete_dataproc_cluster' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T15:13:26+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T15:13:26+00:00'
[2025-09-20 15:20:18.151239+00:00] {taskinstance.py:733} INFO - ::endgroup::
[2025-09-20 15:20:18.193818+00:00] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-09-20 15:20:18.194218+00:00] {dataproc.py:1027} INFO - Deleting cluster: hadoop-cluster-new
[2025-09-20 15:20:18.195080+00:00] {credentials_provider.py:410} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2025-09-20 15:21:31.253636+00:00] {dataproc.py:987} INFO - Cluster deleted.
[2025-09-20 15:21:31.294827+00:00] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20 15:21:31.296004+00:00] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=orders_backfilling_dag, task_id=delete_dataproc_cluster, run_id=manual__2025-09-20T15:13:26+00:00, execution_date=20250920T151326, start_date=20250920T152017, end_date=20250920T152131
[2025-09-20 15:21:31.437289+00:00] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-20 15:21:31.481955+00:00] {taskinstance.py:3904} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20 15:21:31.485372+00:00] {local_task_job_runner.py:245} INFO - ::endgroup::
